name: OpenSSL Playground

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest
    
    steps:
# WITHOUT SALT
      - name: Encrypt Password - No Salt
        id: encrypt
        env:
          ENCRYPTION_KEY: "hUgdkUgYjKapPQ"
          PASSWORD: "9k5sPplOnoo8YclflraRXg8u8nK3bZ0b"
        run: |
          echo $PASSWORD | openssl enc -aes-256-cbc -pbkdf2 -a -nosalt -pass "pass:$ENCRYPTION_KEY"
      
    # WITH SALT
      - name: Encrypt Password - Salt
        id: encrypt2
        env:
          ENCRYPTION_KEY: "kJSOhdhPqwEHfwO"
          PASSWORD: "Vv83nWkdAiqq0zVqpjYa1NTDHlP8UuHK"
        run: |
          echo $PASSWORD | openssl enc -aes-256-cbc -pbkdf2 -a -S "231b12580a08d538" -pass "pass:$ENCRYPTION_KEY"
